create table telefone
(
   id integer generated by default as identity,
   ddd varchar (255),
   numero varchar (255),
   pessoa_id integer,
   primary key (id)
);

alter table telefone add constraint FKedoksohi002ejhppo5nhd7i4n foreign key (pessoa_id) references pessoas;