    create table enderecos (
       id integer generated by default as identity,
        cidade varchar(255),
        numero varchar(255),
        rua varchar(255),
        pessoa_id integer,
        primary key (id)
    );
    
	alter table enderecos 
       add constraint FK4uegllbf38r29n8a1h5m9ev7q 
       foreign key (pessoa_id) 
       references pessoas;