create table consultas
(
   id integer generated by default as identity,
   data date,
   medico_fk integer,
   paciente_fk integer,
   primary key (id)
);

alter table consultas add constraint FKj9taq1pmiga7wib9casqgyxea foreign key (medico_fk) references medicos;
alter table consultas add constraint FKhhj32nc650727knma95pnft0l foreign key (paciente_fk) references pacientes;